---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: gannett/gci-centos7

suites:
- name: default
  run_list:
    - recipe[yum::default]
    - recipe[vsftpd::default]
  attributes:
    vsftpd:
      config:
        listen_address: 127.0.0.1
      allowed:
        - vagrant
      chroot:
        - vagrant
